GET http://localhost:3000/   HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/context HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/session HTTP/1.1
Content-Type: application/json

{
    "username": "cia"
}

###
PUT http://localhost:3000/profiles/2/username HTTP/1.1
Authorization: 2
Content-Type: application/json

{
    "username":"simi"
}

###
PUT http://localhost:3000/profiles/1/followed/2 HTTP/1.1
Authorization: 1
Content-Type: application/json

{
    "uid": 2,
    "username":"simi"
}

