GET http://localhost:3000/   HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/context HTTP/1.1
Content-Type: application/json

###
//CREATE USER
POST http://localhost:3000/session HTTP/1.1
Content-Type: application/json

{
    "username": "cia"
}

###
//CHANGE USER
PUT http://localhost:3000/profiles/1/username HTTP/1.1
Authorization: 1
Content-Type: application/json

{
    "username":"simi"
}

###
//FOLLOW USERNAME
PUT http://localhost:3000/profiles/1/followed/2 HTTP/1.1
Authorization: 1
Content-Type: application/json

{
    "uid": 2,
    "username":"simi"
}

###
//GET USER PROFILE
GET http://localhost:3000/profiles/1/profile HTTP/1.1
Authorization: 1
//Content-Type: application/json
